name: Angular CI/CD

on:
  push:
    branches:
      - master  # ou main si ta branche est main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    # - name: Run unit tests
    #   run: npm run test -- --watch=false --browsers=ChromeHeadless
    #   env:
    #     CHROME_BIN: chromium-browser

    - name: Build Angular
      run: npm run build -- --configuration production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/mon-projet-angular
